import {MODULES,LESSONS,LESSON_BY_ID,PHASES} from './curriculum.js';
import {getValue,putValue,lessonStatus,answerQuestion,exportState,importState,downloadFile,legacyCount,storageWarning} from './state.js';
import {LABS,labMarkup,bindLab,escapeHTML as e} from './labs.js';
import {syncConfig,configureSync,clearSync,synchronize} from './sync.js';
import {projectMarkup,bindProject} from './project.js';

const app=document.querySelector('#app');
const taskDrafts=new Map(),noteDrafts=new Map();
let route={view:'home'},sectionIndex=0,labKind='backtest',toastTimer;
const h=(id,label,cls='')=>`<button class="${cls}" data-go="${id}">${label}</button>`;
const active=()=>LESSON_BY_ID[route.lessonId] || LESSONS[0];
const percent=()=>Math.round(LESSONS.filter(l=>lessonStatus(l).complete).length/LESSONS.length*100);
function go(path){location.hash=path;}
function resume(){const point=getValue('location',{lessonId:LESSONS[0].id,phase:'concept'});go(`learn/${LESSON_BY_ID[point.lessonId]?point.lessonId:LESSONS[0].id}/${PHASES.some(p=>p.id===point.phase)?point.phase:'concept'}/${point.section||0}`);}
function notify(text){const node=document.querySelector('#toast');node.textContent=text;node.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.hidden=true,5500);}
function putSafely(key,value){try{putValue(key,value);if(storageWarning)notify(storageWarning);return true;}catch(error){notify(error.message);return false;}}
function shell(){
  app.innerHTML=`<header class="topbar"><button class="icon-button mobile-menu" aria-label="打开课程目录">☰</button><button class="brand" data-go="home"><span class="brand-symbol">q<span>.</span></span><span><strong>量化学堂</strong><small>LEARN · BUILD · VERIFY</small></span></button><nav class="top-nav" aria-label="主要导航">${h('home','学习路径')}${h('labs','实验室')}${h('review','复习本')}${h('project','策略项目')}</nav><div class="top-actions"><button class="icon-button" data-search aria-label="搜索课程与概念">⌕</button><button class="sync-trigger" data-sync><i></i><span>云同步</span></button></div></header><div class="workspace"><aside class="sidebar" aria-label="课程目录"></aside><main id="main" tabindex="-1"></main></div><dialog id="dialog"></dialog><div id="toast" class="toast" role="status" hidden></div>`;
  app.addEventListener('click',event=>{
    const b=event.target.closest('[data-go]');if(b)go(b.dataset.go);
    if(event.target.closest('[data-sync]'))openSync();
    if(event.target.closest('[data-search]'))openSearch();
    if(event.target.closest('.mobile-menu'))document.body.classList.toggle('menu-open');
    if(event.target.closest('[data-resume]'))resume();
  });
  window.addEventListener('hashchange',render);
  window.addEventListener('academy-sync',event=>{document.querySelector('.sync-trigger span').textContent=event.detail;});
  window.addEventListener('academy-remote',()=>{renderSidebar();notify('云端记录已合并。重新打开当前学习页即可查看最新内容。');});
  window.addEventListener('beforeunload',event=>{if(taskDrafts.size||noteDrafts.size){event.preventDefault();event.returnValue='';}});
  document.addEventListener('keydown',event=>{
    if(document.querySelector('dialog[open]') || event.target.closest('input,textarea,select'))return;
    if(event.altKey && ['ArrowLeft','ArrowRight'].includes(event.key) && route.view==='learn'){event.preventDefault();movePhase(event.key==='ArrowRight'?1:-1);}
  });render();
}
function parseRoute(){const [view,lessonId,phase,section]=location.hash.slice(1).split('/');const lesson=LESSON_BY_ID[lessonId]||LESSONS[0];return {view:['home','learn','labs','review','project'].includes(view)?view:'home',lessonId:lesson.id,phase:PHASES.some(p=>p.id===phase)?phase:'concept',section:Math.min(lesson.sections.length-1,Math.max(0,Number.isInteger(Number(section))?Number(section):0))};}
function render(){
  route=parseRoute();sectionIndex=route.section;
  document.body.classList.remove('menu-open');renderSidebar();
  for(const b of document.querySelectorAll('.top-nav button'))b.classList.toggle('active',b.dataset.go===route.view || route.view==='learn'&&b.dataset.go==='home');
  if(route.view==='learn'){putSafely('location',{lessonId:route.lessonId,phase:route.phase,section:sectionIndex});renderLesson();}
  else if(route.view==='labs')renderLabs();else if(route.view==='review')renderReview();else if(route.view==='project')renderProject();else renderHome();
  if(storageWarning)notify(storageWarning);
}
function renderSidebar(){
  const sidebar=document.querySelector('.sidebar'),current=active();
  sidebar.innerHTML=`<div class="sidebar-head"><span class="eyebrow">YOUR LEARNING MAP</span><strong>一步一步，建立能力</strong><small>股票与 ETF · Python 零基础</small></div><div class="module-list">${MODULES.map((module,i)=>{const count=module.lessons.filter(l=>lessonStatus(l).complete).length;return `<details ${route.view==='learn'&&current.moduleId===module.id?'open':''}><summary><span class="module-num">${String(i+1).padStart(2,'0')}</span><span><strong>${e(module.subtitle)}</strong><small>${count} / ${module.lessons.length} 节记录完整</small></span><b>⌄</b></summary><div class="lesson-links">${module.lessons.map(l=>`<button data-go="learn/${l.id}/concept" class="${route.view==='learn'&&l.id===route.lessonId?'active':''}"><i>${lessonStatus(l).complete?'✓':'·'}</i>${e(l.title)}</button>`).join('')}</div></details>`;}).join('')}</div><div class="sidebar-bottom"><div><span>学习记录完成度</span><strong>${percent()}%</strong></div><div class="meter"><i style="width:${percent()}%"></i></div><small>作业自评与实验留档不等于实盘认证</small></div>`;
}
function renderHome(){
  const done=LESSONS.filter(l=>lessonStatus(l).complete).length,point=getValue('location'),current=LESSON_BY_ID[point?.lessonId]||LESSONS[0],old=legacyCount();
  const main=document.querySelector('#main');main.className='page-scroll';
  main.innerHTML=`<div class="home-hero"><div class="hero-copy"><span class="eyebrow">QUANT ACADEMY / PRACTICE EDITION</span><h1>把每一个概念，<br>变成你能做的事<span>。</span></h1><p>从第一行 Python，到一份能被复核的股票与 ETF 策略研究。理解机制，亲手验证，再用证据判断。</p><div class="hero-actions"><button class="primary" data-resume>${point?'继续上次学习':'开始第一课'} <span>↗</span></button><button class="text-button" data-go="labs">先体验一个实验 →</button></div></div><div class="hero-art" aria-hidden="true"><span class="art-note">HYPOTHESIS → EVIDENCE</span><div class="art-axis"></div><svg viewBox="0 0 360 180"><path d="M0 148L40 140L75 151L110 109L140 115L170 70L210 94L250 36L290 56L340 12" fill="none" stroke="#cce69b" stroke-width="3"/><path d="M0 155L40 153L75 139L110 144L140 121L170 130L210 118L250 101L290 108L340 85" fill="none" stroke="#92afa3" stroke-width="2" stroke-dasharray="5 7"/></svg><div class="art-caption"><span>先提出问题</span><b>再让数据回答。</b></div><small>示意曲线 · 非收益表现</small></div></div><div class="home-stats"><div><strong>30</strong><span>深度课节</span></div><div><strong>60</strong><span>理解检查</span></div><div><strong>7</strong><span>交互实验</span></div><div><strong>1</strong><span>完整策略项目</span></div></div><section class="continue-card"><div><span class="eyebrow">YOUR NEXT STEP</span><h2>${e(current.title)}</h2><p>${e(current.goal)}</p></div><div><span>${done} / ${LESSONS.length} 节学习记录完整</span><button class="secondary" data-resume>进入学习空间 →</button></div></section>${old?`<p class="migration-note">已保留旧版 ${old} 节完成记录与云同步配置。新版作业与测验重新建立证据，旧进度不会直接计为新版掌握度。</p>`:''}<div class="section-title"><div><span class="eyebrow">THE CURRICULUM</span><h2>一条能走通的研究路径</h2></div><span>每课：概念 → 推导 → 实验 → 检验 → 应用</span></div><div class="curriculum-grid">${MODULES.map((m,i)=>`<button class="module-card" data-go="learn/${m.lessons[0].id}/concept"><span class="module-card-top"><b>${String(i+1).padStart(2,'0')}</b><small>${m.lessons.length} 课 · ${m.lessons.reduce((s,l)=>s+l.minutes,0)} 分钟起</small></span><h3>${e(m.title)}</h3><p>${e(m.description)}</p><span class="card-bottom">${e(m.subtitle)} <b>↗</b></span></button>`).join('')}</div><div class="home-note"><strong>学习成果应该是什么？</strong><p>能解释假设、清洗数据、写出回测、识别失真、计算风险，并完成有记录的前向模拟。最终是否适合实盘，要结合真实证据、交易条件和资金承受能力判断；课程不能承诺盈利。</p></div>`;
}
function sourceList(l){return `<details class="sources"><summary>原始资料与进一步阅读 · ${l.sources.length} 项</summary><ul>${l.sources.map(s=>`<li><a href="${e(s.url)}" target="_blank" rel="noopener noreferrer">${e(s.title)} ↗</a></li>`).join('')}</ul><p>市场规则与软件版本以对应官方说明为准，不同市场规则不能直接套用。</p></details>`;}
function renderLesson(){
  const l=active(),index=LESSONS.findIndex(x=>x.id===l.id),phase=PHASES.findIndex(p=>p.id===route.phase),main=document.querySelector('#main');main.className='lesson-workspace';
  main.innerHTML=`<header class="lesson-header"><div><span>${String(l.moduleIndex+1).padStart(2,'0')} / ${e(l.moduleTitle)}</span><h1>${e(l.title)}</h1></div><button class="secondary small" data-note>学习笔记 ✎</button></header><nav class="phase-nav" aria-label="学习步骤">${PHASES.map((p,i)=>`<button data-go="learn/${l.id}/${p.id}" ${phase===i?'aria-current="step"':''}><i>${String(i+1).padStart(2,'0')}</i><span>${p.title}</span></button>`).join('')}</nav><div class="lesson-scroll"><div id="phase-content"></div></div><footer class="learning-footer"><button class="text-button" data-prev ${index===0&&phase===0?'disabled':''}>← <span>上一步</span></button><div><span>第 ${index+1} / ${LESSONS.length} 课</span><small>${e(PHASES[phase].title)} · ${phase+1} / 5</small></div><button class="primary" data-next>${phase===4?(index===LESSONS.length-1?'进入策略项目':'继续下一课'):PHASES[phase+1].title} →</button></footer>`;
  main.querySelector('[data-prev]').onclick=()=>movePhase(-1);main.querySelector('[data-next]').onclick=()=>movePhase(1);main.querySelector('[data-note]').onclick=()=>openNote(l);renderPhase();
}
function renderPhase(){
  const l=active(),node=document.querySelector('#phase-content');
  if(route.phase==='concept'){
    sectionIndex=Math.min(sectionIndex,l.sections.length-1);const s=l.sections[sectionIndex];
    node.innerHTML=`<div class="lesson-goal"><span>这一课，你将能够</span><p>${e(l.goal)}</p><small>开始前：${l.prerequisites.map(e).join(' · ')} / 建议 ${l.minutes} 分钟起，作业另计</small></div><div class="concept-pager" aria-label="概念段落">${l.sections.map((s,i)=>`<button data-section="${i}" class="${i===sectionIndex?'active':''}">${i+1}. ${e(s.title)}</button>`).join('')}</div><article class="concept-article"><span class="eyebrow">CONCEPT ${sectionIndex+1} / ${l.sections.length}</span><h2>${e(s.title)}</h2><p>${e(s.body)}</p>${s.bullets?`<ul>${s.bullets.map(t=>`<li>${e(t)}</li>`).join('')}</ul>`:''}<div class="concept-bottom"><span>${sectionIndex+1} / ${l.sections.length}</span><button class="text-button" data-section-next>${sectionIndex<l.sections.length-1?'继续讲解':'进入推导'} →</button></div></article><details class="explain-details"><summary>换个角度理解 · 类比与公式</summary><p>${e(l.analogy)}</p><div class="formula">${e(l.formula.expression)}</div><dl>${l.formula.variables.map(v=>`<dt>${e(v.symbol)}</dt><dd>${e(v.meaning)}</dd>`).join('')}</dl><p>${e(l.formula.interpretation)}</p></details>${sourceList(l)}`;
    node.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>go(`learn/${l.id}/concept/${b.dataset.section}`));
    node.querySelector('[data-section-next]').onclick=()=>movePhase(1);
    document.querySelector('[data-next]').textContent=sectionIndex<l.sections.length-1?'继续讲解 →':'进入推导 →';
    document.querySelector('[data-prev]').disabled=LESSONS[0].id===l.id&&sectionIndex===0;
    document.querySelector('.learning-footer small').textContent=`概念 ${sectionIndex+1} / ${l.sections.length} 段 · 1 / 5 步`;
  }else if(route.phase==='worked'){
    node.innerHTML=`<span class="eyebrow">WORKED EXAMPLE</span><h2 class="phase-title">${e(l.worked.title)}</h2><p class="phase-lead">用纸笔先算一遍，再逐步核对。每个数值都应有来源。</p><ol class="worked-steps">${l.worked.steps.map((s,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><p>${e(s)}</p></li>`).join('')}</ol><div class="result-card"><span>得到什么结论</span><p>${e(l.worked.result)}</p></div><h3>这几处最容易出错</h3><ul class="pitfalls">${l.pitfalls.map(p=>`<li>${e(p)}</li>`).join('')}</ul>`;
  }else if(route.phase==='lab'){node.innerHTML=labMarkup(l.lab);bindLab(node,{lessonId:l.id,notify,onSave:renderSidebar});
  }else if(route.phase==='check'){
    node.innerHTML=`<span class="eyebrow">CHECK YOUR UNDERSTANDING</span><h2 class="phase-title">能解释，才算走近理解</h2><p class="phase-lead">先独立作答，再阅读反馈。错误会进入复习本，重新作答后才更新结果。</p>${l.checks.map((q,i)=>questionMarkup(l,q,i)).join('')}<p class="hint">正确率反映这些题目的最近结果，不代表整体交易能力。</p>`;
    node.querySelectorAll('[data-question]').forEach(form=>form.onsubmit=event=>{event.preventDefault();const q=l.checks.find(q=>q.id===form.dataset.question),answer=new FormData(form).get('answer');if(answer===null||String(answer).trim()===''){notify('先填写答案。');return;}try{const result=answerQuestion(l,q,answer);form.querySelector('[data-feedback]').innerHTML=feedback(q,result);renderSidebar();}catch(error){notify(error.message);}});
  }else{
    const saved=taskDrafts.get(l.id)||getValue(`task:${l.id}`,{}),status=lessonStatus(l);
    node.innerHTML=`<span class="eyebrow">TRANSFER TO YOUR OWN WORK</span><h2 class="phase-title">把方法带出这道例题</h2><div class="task-brief"><p>${e(l.task.prompt)}</p><span>交付物</span><strong>${e(l.task.deliverable)}</strong></div><div class="code-header"><h3>从这段代码开始</h3><button class="text-button" data-download-code>下载 .py ↘</button></div><pre><code>${e(l.task.starterCode)}</code></pre><p class="hint">代码在你自己的电脑运行。浏览器实验不等于已经运行 Python；从第 1 课学习环境安装，遇到报错先检查解释器和依赖。</p><form id="task-form"><label class="field"><span>你的结果、证据位置与解释（至少 80 字）</span><textarea name="text" rows="6" maxlength="8000" placeholder="记录运行输出、手工核对、失败结果和文件位置；不要粘贴账户凭证。">${e(saved.text||'')}</textarea></label><p class="rubric-label">逐项自评：这部分是你的确认，系统不会自动评判文字正确性。</p>${l.task.rubric.map((r,i)=>`<label class="check-label"><input type="checkbox" name="rubric" value="${i}" ${saved.rubric?.includes(i)?'checked':''}>${e(r)}</label>`).join('')}<button type="submit" class="primary">保存迁移作业</button></form><div class="completion-note">${status.complete?'本节学习记录已齐备，可继续下一课。':`本节还需：${[status.right<status.total?'完成理解检查':'',!status.exercise?'保存实验解释':'',!status.task?'填写作业并逐项自评':''].filter(Boolean).join('、')}。`} <span>学习记录齐备不等于实盘能力认证。</span></div>`;
    node.querySelector('[data-download-code]').onclick=()=>downloadFile(`${l.id}.py`,l.task.starterCode,'text/x-python;charset=utf-8');
    node.querySelector('#task-form').oninput=event=>{const f=new FormData(event.currentTarget);taskDrafts.set(l.id,{text:String(f.get('text')),rubric:f.getAll('rubric').map(Number)});};
    node.querySelector('#task-form').onsubmit=event=>{event.preventDefault();const f=new FormData(event.target);if(!putSafely(`task:${l.id}`,{text:String(f.get('text')),rubric:f.getAll('rubric').map(Number)}))return;taskDrafts.delete(l.id);notify(storageWarning||'作业已保存；自评与文本长度仅检查留档完整性。');renderPhase();renderSidebar();};
  }
}
function questionMarkup(l,q,i){const old=getValue(`quiz:${q.id}`);return `<form class="question" data-question="${q.id}"><div class="question-label"><span>CHECK ${String(i+1).padStart(2,'0')}</span><small>${q.type==='number'?'数值推导':'判断与选择'}</small></div><h3>${e(q.prompt)}</h3>${q.type==='choice'?`<fieldset><legend class="sr-only">选择答案</legend>${q.options.map((o,i)=>`<label class="answer-option"><input type="radio" name="answer" value="${i}" ${old?.answer===String(i)?'checked':''} required><b>${String.fromCharCode(65+i)}</b><span>${e(o)}</span></label>`).join('')}</fieldset>`:`<label class="field"><span>按题目要求填写数值（不要添加单位）</span><input type="number" step="any" name="answer" value="${e(old?.answer || '')}" required></label>`}<button class="secondary" type="submit">检查答案 →</button><div data-feedback aria-live="polite">${old?feedback(q,old):''}</div></form>`;}
function feedback(q,r){return `<div class="feedback ${r.correct?'correct':'incorrect'}"><strong>${r.correct?'计算 / 判断正确':'先停一步，检查思路'}</strong><p>${e(!r.correct&&q.wrongExplanations?.[Number(r.answer)] || q.explanation)}</p>${!r.correct?`<p>参考${q.type==='choice'?'选项':'数值'}：${q.type==='choice'?e(q.options[q.answer]):q.answer}。请理解原因后重新作答。</p>`:''}</div>`;}
function movePhase(direction){const l=active(),i=PHASES.findIndex(p=>p.id===route.phase),j=LESSONS.findIndex(x=>x.id===l.id);if(route.phase==='concept'&&sectionIndex+direction>=0&&sectionIndex+direction<l.sections.length){go(`learn/${l.id}/concept/${sectionIndex+direction}`);return;}if(i+direction<0){if(j>0)go(`learn/${LESSONS[j-1].id}/task`);}else if(i+direction>=PHASES.length){if(j<LESSONS.length-1)go(`learn/${LESSONS[j+1].id}/concept`);else go('project');}else go(`learn/${l.id}/${PHASES[i+direction].id}/${i+direction===0?l.sections.length-1:0}`);}
function renderLabs(){const main=document.querySelector('#main');main.className='page-scroll';main.innerHTML=`<div class="page-heading"><div><span class="eyebrow">THE SANDBOX</span><h1>让参数告诉你为什么</h1><p>七个可以反复改变条件的实验。先预测，再运行，最后记录。</p></div></div><nav class="local-tabs" aria-label="实验选择">${Object.entries(LABS).map(([id,label])=>`<button data-lab-choice="${id}" class="${id===labKind?'active':''}">${label}</button>`).join('')}</nav><div id="standalone-lab">${labMarkup(labKind)}</div>`;main.querySelectorAll('[data-lab-choice]').forEach(b=>b.onclick=()=>{labKind=b.dataset.labChoice;renderLabs();});bindLab(main,{notify});}
function renderReview(){
  const main=document.querySelector('#main');main.className='page-scroll';const items=LESSONS.flatMap(l=>l.checks.map(q=>({l,q,r:getValue(`quiz:${q.id}`)}))).filter(x=>x.r),wrong=items.filter(x=>!x.r.correct),due=items.filter(x=>x.r.reviewAt<=Date.now());
  main.innerHTML=`<div class="page-heading"><div><span class="eyebrow">RETRIEVE, DON'T REREAD</span><h1>把薄弱处练扎实</h1><p>复习采用 1、3、7、14、30 天间隔；答错会重新缩短间隔。</p></div></div><div class="readiness-grid"><article><span>最近答对</span><strong>${items.filter(x=>x.r.correct).length}<small> / ${LESSONS.reduce((s,l)=>s+l.checks.length,0)}</small></strong></article><article><span>目前待纠正</span><strong>${wrong.length}</strong></article><article><span>今天到期复习</span><strong>${due.length}</strong></article></div><h2>优先练这些</h2><div class="review-list">${[...new Map([...wrong,...due].map(x=>[x.q.id,x])).values()].map(({l,q,r})=>`<article><span class="eyebrow">${e(l.moduleTitle)}</span><h3>${e(q.prompt)}</h3><p>累计错误 ${r.mistakes} 次 · ${r.correct?'到期再回忆':'最近仍需纠正'}</p><button class="secondary" data-go="learn/${l.id}/check">重新作答 →</button></article>`).join('')||'<div class="empty"><strong>现在没有待复习题。</strong><p>进入课程，完成理解检查；错题和到期复习会出现在这里。</p></div>'}</div><h2>每个模块的证据覆盖</h2><div class="mastery-list">${MODULES.map(m=>{const qs=m.lessons.flatMap(l=>l.checks),seen=qs.filter(q=>getValue(`quiz:${q.id}`)),right=seen.filter(q=>getValue(`quiz:${q.id}`).correct);return `<div><strong>${e(m.subtitle)}</strong><div class="meter"><i style="width:${right.length/qs.length*100}%"></i></div><span>最近答对 ${right.length}/${qs.length} · 已测 ${seen.length}/${qs.length}</span></div>`;}).join('')}</div>`;
}
function renderProject(){const main=document.querySelector('#main');main.className='page-scroll';main.innerHTML=projectMarkup(LESSONS);bindProject(main,LESSONS,{notify,rerender:renderProject});}
function openDialog(title,body){const d=document.querySelector('#dialog');d.innerHTML=`<div class="dialog-header"><h2>${title}</h2><button class="icon-button" data-close aria-label="关闭对话框">×</button></div><div class="dialog-body">${body}</div>`;d.querySelector('[data-close]').onclick=()=>d.close();d.showModal();return d;}
function openNote(l){const d=openDialog('我的学习笔记',`<span class="eyebrow">${e(l.title)}</span><p>用自己的话解释机制，记下不确定的地方和下一次验证。草稿在本页切换时保留，点击保存后才写入学习记录。</p><label class="field"><span>个人笔记</span><textarea rows="12" maxlength="8000">${e(noteDrafts.get(l.id)??getValue(`note:${l.id}`,''))}</textarea></label><button class="primary" data-save-note>保存笔记</button>`);d.querySelector('textarea').oninput=event=>noteDrafts.set(l.id,event.target.value);d.querySelector('[data-save-note]').onclick=()=>{if(!putSafely(`note:${l.id}`,d.querySelector('textarea').value))return;noteDrafts.delete(l.id);notify(storageWarning||'笔记已保存，可随云端进度同步。');d.close();};}
function openSearch(){const d=openDialog('搜索课程与概念','<label class="field"><span>关键词</span><input type="search" placeholder="例如：夏普、未来函数、订单、Python"></label><div class="search-results" aria-live="polite"></div>');d.querySelector('input').oninput=event=>{const term=event.target.value.trim().toLowerCase();const matches=term?LESSONS.filter(l=>`${l.title} ${l.goal} ${l.sections.map(s=>s.title+' '+s.body).join(' ')}`.toLowerCase().includes(term)):[];d.querySelector('.search-results').innerHTML=matches.slice(0,20).map(l=>`<button data-result="${l.id}"><strong>${e(l.title)}</strong><small>${e(l.moduleTitle)}</small></button>`).join('')||(term?'<p>没有找到，试试更短的关键词。</p>':'');d.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{d.close();go(`learn/${b.dataset.result}/concept`);});};}
function openSync(){
  const c=syncConfig(),d=openDialog('跨设备继续学习',`<p>用 GitHub Secret Gist 同步笔记、作业、实验和项目记录。Secret Gist 不公开列出，但知道链接的人可能读取；请勿放入账户凭证或个人财务资料。</p><form id="sync-form"><label class="field"><span>GitHub Token（仅需 gist 权限）</span><input type="password" name="token" autocomplete="new-password" placeholder="${c.hasToken?'已保存；留空表示继续使用':'ghp_…'}"></label><label class="field"><span>Gist ID（第一台设备首次同步留空）</span><input name="gist" value="${e(c.gistId)}" placeholder="换设备填写同一个 Gist ID"></label><label class="check-label"><input type="checkbox" name="session" ${c.sessionOnly?'checked':''}>Token 仅保留在本次浏览器会话</label><div class="button-row"><button class="primary" type="submit">合并并同步</button><button type="button" class="secondary" data-pull>仅拉取</button><button type="button" class="text-button" data-clear>清除连接</button></div><p data-sync-status class="hint" role="status">${c.lastSyncedAt?'上次成功：'+new Date(c.lastSyncedAt).toLocaleString():'本地进度自动保存；云同步需要你配置连接。'}</p></form><details class="explain-details"><summary>如何获取 Token 与接续旧版？</summary><p><a href="https://github.com/settings/tokens/new?scopes=gist&description=Quant%20Academy%20Cloud%20Sync" target="_blank" rel="noopener noreferrer">打开 GitHub Token 申请页 ↗</a>，仅选 gist 并设置有效期。Token 只发给 GitHub 官方 API，不写入进度文件。旧版 Gist ID 可继续用；升级后其他设备也须刷新为新版。</p></details><div class="backup-row"><button class="secondary" data-export>导出完整备份</button><label class="file-button">导入并合并<input type="file" data-import accept=".json,application/json" hidden></label></div>`);
  const sync=async pullOnly=>{const form=d.querySelector('form'),f=new FormData(form),status=d.querySelector('[data-sync-status]'),buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{configureSync({newToken:f.get('token'),gistId:f.get('gist'),sessionOnly:f.get('session')==='on'});status.textContent='正在与 GitHub 同步…';const v=await synchronize({pullOnly});form.elements.gist.value=v.gistId;form.elements.token.value='';status.textContent='同步成功。其他设备填写此 Gist ID 并拉取即可继续。';}catch(error){status.textContent=error.message;}finally{buttons.forEach(b=>b.disabled=false);}};
  d.querySelector('form').onsubmit=event=>{event.preventDefault();sync(false);};d.querySelector('[data-pull]').onclick=()=>sync(true);
  d.querySelector('[data-clear]').onclick=()=>{clearSync();d.querySelector('form').reset();d.querySelector('input[name="gist"]').value='';d.querySelector('[data-sync-status]').textContent='连接已清除，本地学习记录保留。';};
  d.querySelector('[data-export]').onclick=()=>downloadFile('quant-academy-backup.json',exportState(),'application/json');
  d.querySelector('[data-import]').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{importState(await file.text());notify('备份已合并。');d.close();render();}catch(error){d.querySelector('[data-sync-status]').textContent=error.message;}};
}
shell();
